name: deploy

on:
  repository_dispatch:
    types: [ deploy ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    environment: staging
    steps:
      - uses: actions/checkout@v3

      - uses: kielabokkie/ssh-key-and-known-hosts-action@v1.3.5
        with:
          ssh-host: 3.95.254.37
          ssh-private-key: ${{ secrets.GH_PRIVATE_KEY }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Deploy
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        run: ./ops.sh --deploy staging
